# Generated by Django 6.1.1 on 2026-09-28 08:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('leave_type', models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave')], max_length=16)),
                ('days', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(366)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allowances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee_id', 'year', 'leave_type'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'year', 'leave_type'), name='unique_allowance_per_year_type'), models.CheckConstraint(condition=models.Q(('days__gte', 0), ('days__lte', 366)), name='allowance_days_in_range'), models.CheckConstraint(condition=models.Q(('leave_type__in', ['CASUAL', 'SICK'])), name='allowance_known_leave_type')],
            },
        ),
    ]
