# Generated by Django 6.1.1 on 2026-09-28 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leave_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='client_request_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.UniqueConstraint(fields=('employee', 'client_request_id'), name='leave_request_unique_client_id'),
        ),
    ]
